name: Automatically assign reviewers

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [opened]
    branches: [ master, devel-actions ]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Team and Persons"
      uses: rowi1de/auto-assign-review-teams@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        teams: "test-team"
